First cut of pyproject.toml version
not working yet:

```
1.515 ERROR: Cannot install freezing-model==0.9.2 and geoalchemy 0.7.3.dev1 (from /tmp/wheels/GeoAlchemy-0.7.3.dev1-py3-none-any.whl) because these package versions have conflicting dependencies.
1.515
1.515 The conflict is caused by:
1.515     The user requested geoalchemy 0.7.3.dev1 (from /tmp/wheels/GeoAlchemy-0.7.3.dev1-py3-none-any.whl)
1.515     freezing-model 0.9.2 depends on geoalchemy 0.7.3.dev1 (from https://github.com/hozn/GeoAlchemy/archive/0.7.3dev1.tar.gz)
1.515
1.515 To fix this you could try to:
1.515 1. loosen the range of package versions you've specified
1.515 2. remove package versions to allow pip to attempt to solve the dependency conflict
1.515
1.667 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
------
Dockerfile:36
--------------------
  34 |     RUN pip3 install --upgrade pip setuptools wheel
  35 |     COPY --from=buildstep /build/wheels /tmp/wheels
  36 | >>> RUN pip3 install /tmp/wheels/*
  37 |
  38 |     EXPOSE 8000
--------------------
ERROR: failed to solve: process "/bin/sh -c pip3 install /tmp/wheels/*" did not complete successfully: exit code: 1
```